const express = require("express");
const router = express.Router();
const authController = require("../controllers/tracker.controller");
router.post("/login", authController.login);
router.post("/set_goal", authController.set_goal);
router.post("/done", authController.done);
router.post("/streakStatus", authController.streakStatus);
router.post("/allStreaks", authController.allStreaks);
router.post("/getLoggedIndata", authController.getLoggedIndata);
router.post("/getWeightDetails", authController.getWeightDetails);
router.post("/addWeight", authController.addWeight);
router.post("/addMeasuremnets", authController.addMeasuremnets);
router.post("/addDiet", authController.addDiet);
router.post("/addPhase", authController.addPhase);
router.post("/newAccount", authController.newAccount);
router.post("/personalDetails", authController.personalDetails);
router.post("/fitnessDetails", authController.fitnessDetails);
router.post("/addWorkout", authController.addWorkout);
router.post("/getAllDiets", authController.getAllDiets);
router.post("/getAllWorkouts", authController.getAllWorkouts);
router.post("/getSingleDiets", authController.getSingleDiets);
router.post("/getSingleWorkout", authController.getSingleWorkout);
router.post("/updateWorkoutName", authController.updateWorkoutName);
router.post("/updateDietName", authController.updateDietName);
router.post("/streaksAllData", authController.streaksAllData);
// router.get("/test", authController.test);

// router.post("/signUp", authController.signUp);
// router.post("/checkUsername", authController.checkUsername);
// router.post("/checkPhonenumber", authController.checkPhonenumber);
// router.post("/checkEmail", authController.checkEmail);
// router.get("/getUserDetails", authenticateToken, authController.getUserDetails);
// router.get("/getLoggedInUser", authenticateToken, authController.getLoggedInUser);
// router.get("/getPersonalDetails", authenticateToken,authController.getPersonalDetails); 
// router.post("/updateMetadata", authController.updateMetadata);
// router.post("/forgot-password", authController.forgotPassword);
// router.post("/reset-password", authController.resetPassword);

module.exports = router;
